export default [
	{
		slug: 'some link',
		tech: 'html',
		offerTitle: 'junior web developer',
		companyName: 'claro que si',
		companySize: 20,
		street: 'ulica',
		city: 'Warszawa',
		empType: 'UoD',
		expLvl: 'Junior',
		salaryFrom: 3000,
		salaryTo: 5000,
		image: 'https://source.unsplash.com/700x400/?logo',
		technology: [
			{
				tech: 'html',
				techLvl: 5,
			},
			{
				tech: 'css',
				techLvl: 4,
			},
			{
				tech: 'js',
				techLvl: 1,
			},
		],
		placeId: 'some place id',
		dateAdd: '12.07.2020',
		description: 'desc1',
	},
	{
		slug: 'some link 2 ',
		tech: 'js',
		offerTitle: 'mid react developer',
		companyName: 'some of the company',
		companySize: 50,
		street: 'ulica2',
		city: 'Poznań',
		empType: 'B2B',
		expLvl: 'Mid',
		salaryFrom: 5000,
		salaryTo: 8000,
		image: 'https://source.unsplash.com/701x400/?logo',
		technology: [
			{
				tech: 'react',
				techLvl: 5,
			},
			{
				tech: 'redux',
				techLvl: 4,
			},
			{
				tech: 'js',
				techLvl: 4,
			},
		],
		placeId: 'some place id2',
		dateAdd: '13.07.2020',
		description: 'desc2',
	},
	{
		slug: 'somelink3',
		tech: 'python',
		offerTitle: 'Junior Data Scientist',
		companyName: 'Perfecto',
		companySize: 500,
		street: 'ulica3',
		city: 'Wrocław',
		empType: 'UoP',
		expLvl: 'Junior',
		salaryFrom: 4000,
		salaryTo: 7000,
		image: 'https://source.unsplash.com/702x400/?logo',
		technology: [
			{
				tech: 'python',
				techLvl: 4,
			},
			{
				tech: 'matplotlib',
				techLvl: 3,
			},
			{
				tech: 'numpy',
				techLvl: 3,
			},
		],
		placeId: 'some place id3',
		dateAdd: '15.07.2020',
		description: 'desc3',
	},
]
